//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public int id { get; set; }
        public int idUsuario { get; set; }
        public int idProducto { get; set; }
        public Nullable<System.DateTime> FechaFactura { get; set; }
        public bool Pagado { get; set; }
        public int Cantidad { get; set; }
        public int PrecioUnidad { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
